image: Visual Studio 2015

environment:
  NODEJS_VERSION: "8"
  PREBUILD_UPLOAD:
    secure: JR/9VrnOU3roUVXpLCz28ei0fWB1NyZmlAE97sWSZZI94xfX1FWqeWDzoHNA/kl1

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:Platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off

branches:
  only:
    - master
    - /^v.*$/

deploy_script: IF "%APPVEYOR_REPO_TAG%" == "true" (npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%)
